version: 1
accounts:
  - name: deneme
    mnemonic: "uncle very salad fever tree bleak useful range cloth afford simple sudden"
    coins:
      - 1000000000000000stake
      - 1000000000000000token
  - name: alice
    coins:
      - 20000token
      - 200000000stake
  - name: bob
    coins:
      - 10000token
      - 100000000stake
faucet:
  name: bob
  coins:
    - 5token
    - 100000stake
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
validators:
  - name: alice
    bonded: 100000000stake
